# .github/workflows/register.yml
name: Register

on:
  push:
    branches:
      - main

jobs:
  register:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run registration script
        run: |
          echo "Name: John Doe"
          echo "Email: ${{ secrets.EMAIL }}" >> registration.txt
          echo "Bitcoin Wallet Address: 1abc123" >> registration.txt
          echo "Form data saved!"
