# .github/workflows/register.yml
name: Register

on:
  push:
    branches:
      - main

jobs:
  register:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install npm dependencies
        run: npm ci

      - name: Run registration script
        run: node app.js
